const ACTIONS = {
    GET: 'GET',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    DELETE_ALL: 'DELETE_ALL',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
};

export default ACTIONS;